package com.example.studentticketexchange;

public class Listing {

    public String gameID;
    public String sellerEmail;
    public Boolean studentTicket;
    public Boolean validated;
    public String section;
    public String message;
    //assume qty will be generated by counting the number of child Tickets associated with a Listing

    Listing(String sellerEmail, Boolean studentTicket, Boolean validated, String section, String message){
        this.gameID = "1";
        this.sellerEmail = sellerEmail;
        this.studentTicket = studentTicket;
        this.validated = validated;
        this.section = section;
        this.message = message;
    }

}
